### ISSUE TITLE
status indicator not working

### ISSUE THREAD

**Issue by nizrdev** [chtake/pi-wol#581]
Hi again,

i just noticed, that the indicator for offline/online of my device is probably not working. See following [screenshot](https://imgur.com/a/7RLO9UX).

My setup works like this:
- pi-wol in docker container with network mode "host"
- docker running on raspi 4 (ip adress: 192.168.XXX.250
- raspi connected to some simple budget layer 2 netgear switch (not managed)
- DESKTOP connected to same switch

The DESKTOP device is powered on, since I am writing this issue on this computer. Waking up is also working fine.

Maybe I have to reconfigure some of my components (i don't know what) or there is a bug?

**Comment by chtake** [comment]
Hi JanNizr,
pi-wol checks the online/offline status with a ping to the network devices. Maybe the firewall on your windows pc is blocking ping responses for the local network. Can you please check from your rpi if "ping 192.168.XXX.250" is working properly?

**Comment by nizrdev** [comment]
Thanks a lot. Windows firewall was blocking ping packets..
